language: go
dist: trusty
go:
  - 1.13.3
services:
  - docker
env:
  global:
    - CGO_ENABLED=0
    - GO111MODULE=on
before_script:
  - docker pull postgres:10.16-alpine
  - docker run -d -e POSTGRES_PASSWORD=vulndb_test -e POSTGRES_USER=vulndb_test -e POSTGRES_DB=vulndb_test \
      --name pg postgres:10.16-alpine
gobuild_args: -a -tags netgo -ldflags '-w'
go_import_path: github.com/adevinta/vulnerability-db
script:
  - go install ./...
  - go test -v -tags integration $(go list ./... | grep -v /vendor/) ./test
  - cd cmd/vulnerability-db-consumer && go build && cd -
after_success:
  - bash -c 'source <(curl -s https://raw.githubusercontent.com/adevinta/vulcan-cicd/master/docker.sh)'
