# Defines the max age, in days an event can have to be considered. Events
# older than this age are discarded. If 0 no events are discarded.
max_event_age = 0
[log]
# log levels: panic, fatal, error, warn, info, debug, trace
level = "trace"

[db]
dialect = "postgres"
host = "localhost"
port = "5440"
user = "vulndb"
password = "vulndb"
sslmode = "disable"
name = "vulndb"

[sqs]
number_of_processors = 1
wait_time = 20
timeout = 30
queue_arn = "arn:aws:sqs:local:012345678900:VulcanLocalhostVulnDBChecks"
endpoint = "http://localhost:4100"

[sns]
topic_arn = "arn:aws:sqs:local:012345678900:VulcanLocalhostChecks"
enabled = false
endpoint = "http://localhost:4100"

[report]
url_replace = "http://localhost:8080|http://localhost:8080"

[maintenance]
# periodical tasks executed in background
# - name: Custom task name
# - type: Task type
# - rate: Time (hours) after which the task will be periodically executed
# - options: Custom option params for each type
#
# available task types:
#  - expire_findings { ttl: Expire time in days, source: findings source name }
#
tasks = [
    {name = "expire_vulcan_findings", type = "expire_findings", rate = 24, options = { ttl=60, source="vulcan" }}
]
